size = 1000
# noOfBots = 4
# initialNumberOfDirt = 5000
dirtSpotSize = 10
priorityZoneSize = 250
priorityZoneColor = "red"
scoreForDirtCollected = 1
priorityAreaMaxLifeTime = 500
priorityAreaCleanedPoints = priorityAreaMaxLifeTime
scoreLossPerDirt = 0.0003
# numberOfMoves = 1000
priorityAreaName = "priorityArea"
